name: CI Pipeline

on:
  push:
    branches:
      - main
      - docker
      - ai

jobs:

  start-ci:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Repository
        run: |
          echo "CI pipeline started"
          echo "Listing project files:"
          ls -la