name: Secrets Scan

on:
  push:
    branches:
      - main
      - docker
      - ai

jobs:

  gitleaks-scan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --verbose